// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fynkygotvuqlsiqmpmbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bmt5Z290dnVxbHNpcW1wbWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTM4OTksImV4cCI6MjA1OTY2OTg5OX0.l7OOAipajIpDV_MCIjv0YTfrI9SL9hNNgw_mvCCuUGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);